# action.yml
name: 'Stack Image'
description: 'Stack Image'
inputs:
  command:
    description: 'Command for stack'
    required: true
    default: 'build'
  packages:
    description: 'additional apt packages to build(separated by space)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.command }}
    - APT_PACKAGES=${{ inputs.packages }}

